baseurl = "https://www.richardsumilang.com/"
languageCode = "en-us"
title = "Richard Sumilang"
theme = "hugo-theme-richardsumilang-dark"

[author]
  name = "Richard Sumilang"
  homepage = "https://www.richardsumilang.com"

[indexes]
  category = "categories"
  tag = "tags"

[params]
  AmazonAffiliate = "https://www.amazon.com?_encoding=UTF8&tag=topseclabrics-20"
  AuthorName = "Richard"
  Bitbucket = "rsumilang"
  Disqus = "richardsumilang"
  Domain = "richardsumilang.com"
  Email = "me@richardsumilang.com"
  Facebook = "rsumilang"
  GitHub = "rsumilang"
  GoogleAdClient = "ca-pub-9583222607083188"
  GooglePlus = "103897788753346013902"
  GoogleTagManagerId = "GTM-TD3RCSD"
  GoogleTagManagerAuth = "j8O4JXfBl0ZE8KUkCt1uKw"
  GoogleTagManagerEnv = "env-7"
  Instagram = "RichardSumilang"
  Linkedin = "richardsumilang"
  Logo = "images/header-logo.png"
  NewsletterUrl = "https://eepurl.com/bwckhL"
  Pinterest = "rsumilang"
  Twitter = "richardsumilang"
  YouTube = "richardsumilang"
  SiteName = "Tech tips, photography, and more."
